name: build-lede

on:
  repository_dispatch:
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  LEDE_REPO: https://github.com/coolsnowwolf/lede
  LEDE_BRANCH: master
  LEDE_CONFIG: ./config/lede/lede.conf
  LEDE_NAME: n60pro
  LEDE_IP: 192.168.10.1
  LEDE_SSID: 778v5
  LEDE_FIRMWARE_TAG: lede
  LEDE_UPLOAD_FIRMWARE: true
  LEDE_UPLOAD_RELEASE: true
  LEDE_UPLOAD_BIN_DIR: false
  TIME_ZONE: Asia/Shanghai
  DEVICE_NAME: netcore_n60-pro
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Free disk space
        uses: BRAINSia/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          mandb: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo -E apt -yqq update
          sudo -E apt -yqq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler dos2unix flex gawk gcc-multilib g++-multilib gettext genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool llvm lrzsz msmtp ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E apt -yqq autoremove --purge
          sudo -E apt -yqq clean
          # 实际上，用下面这行可以替代上面的一些工作
          # sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
          sudo timedatectl set-timezone "$TIME_ZONE"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir

      - name: Initialization values
        run: |
          echo "LEDE_KVER=none" >> $GITHUB_ENV
          echo "LEDE_LIST=none" >> $GITHUB_ENV

      - name: Clone source code
        working-directory: /workdir
        run: |
          df -hT $PWD
          git clone $LEDE_REPO -b $LEDE_BRANCH openwrt
          ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

      - name: Check scripts
        run: |
          # 为sh脚本赋予可执行权限
          # find ./ -maxdepth 4 -type f -iregex ".*\(txt\|sh\)$" -exec dos2unix {} \; -exec chmod +x {} \;
          # find ./ -maxdepth 4 -type f -iregex ".*\(sh\)$" -exec dos2unix {} \; -exec chmod +x {} \;
          find ./ -maxdepth 4 -type f -name "*.sh" -exec dos2unix {} \; -exec chmod +x {} \;

      - name: Update feeds
        run: cd openwrt && ./scripts/feeds update -a

      - name: Install feeds
        run: cd openwrt && ./scripts/feeds install -a

      - name: Custom packages
        run: |
          # Check scripts中已授权，故注释掉下面两行
          # chmod +x $GITHUB_WORKSPACE/scripts/lede/packages.sh
          # chmod +x $GITHUB_WORKSPACE/scripts/lede/handles.sh
          cd openwrt/package/
          $GITHUB_WORKSPACE/scripts/lede/packages.sh
          $GITHUB_WORKSPACE/scripts/lede/handles.sh

      - name: Load custom configuration
        run: |
          [ -e files ] && mv files openwrt/files
          [ -e $LEDE_CONFIG ] && mv $LEDE_CONFIG openwrt/.config
          # Check scripts中已授权，故注释掉下面两行
          # chmod +x $GITHUB_WORKSPACE/scripts/lede/settings.sh
          cd openwrt
          $GITHUB_WORKSPACE/scripts/lede/settings.sh

      - name: Download package
        id: package
        run: |
          cd openwrt
          make defconfig
          make download -j$(nproc)
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile the firmware
        id: compile
        run: |
          cd openwrt
          echo -e "$(nproc) thread compile"
          make -j$(nproc) || make -j1 || make -j1 V=s
          echo "status=success" >> $GITHUB_OUTPUT
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

      - name: Check space usage
        if: (!cancelled())
        run: df -hT

      - name: Upload bin directory
        uses: actions/upload-artifact@main
        if: steps.compile.outputs.status == 'success' && env.LEDE_UPLOAD_BIN_DIR == 'true'
        with:
          name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
          path: openwrt/bin

      - name: Organize files
        id: organize
        if: env.LEDE_UPLOAD_FIRMWARE == 'true' && !cancelled()
        run: |
          cd openwrt/bin/targets/*/*
          rm -rf packages
          echo "LEDE_KVER=$(find openwrt/bin/targets/ -type f -name "*.manifest" -exec grep -oP '^kernel - \K[\d\.]+' {} \;)" >> $GITHUB_ENV
          echo "LEDE_LIST=$(find openwrt/bin/targets/ -type f -name "*.manifest" -exec grep -oP '^luci-(app|theme)[^ ]*' {} \; | tr '\n' ' ')" >> $GITHUB_ENV
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Upload firmware directory
        uses: actions/upload-artifact@main
        if: steps.organize.outputs.status == 'success' && !cancelled()
        with:
          name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
          path: ${{ env.FIRMWARE }}

      - name: Generate release tag
        id: tag
        if: env.LEDE_UPLOAD_RELEASE == 'true' && !cancelled()
        run: |
          echo "release_tag=$(TZ=UTC-8 date +"%y.%m.%d-%H.%M.%S")-${{ env.LEDE_FIRMWARE_TAG }}" >> $GITHUB_OUTPUT
          touch release.txt
          [ ${UPLOAD_GOFILE} = true && ${{ steps.gofile.outputs.url }} ] && echo "?? [GoFile](${{ steps.gofile.outputs.url }})" >> release.txt
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Upload firmware to release
        uses: softprops/action-gh-release@master
        if: steps.tag.outputs.status == 'success' && !cancelled()
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          # body_path: release.txt
          # files: ${{ env.FIRMWARE }}/*
          files: |
            ${{ env.FIRMWARE }}/openwrt-*.bin
            ${{ env.FIRMWARE }}/openwrt-*.manifest
          body: |
            源码：${{env.LEDE_REPO}}
            分支：${{env.LEDE_BRANCH}}

            内核版本：${{env.LEDE_KVER}}
            插件列表：${{env.LEDE_LIST}}

      #- name: Delete workflow runs
      #  uses: Mattraks/delete-workflow-runs@main
      #  with:
      #    retain_days: 0
      #    keep_minimum_runs: 2

      #- name: Remove old Releases
      #  uses: dev-drprasad/delete-older-releases@master
      #  if: env.LEDE_UPLOAD_RELEASE == 'true' && !cancelled()
      #  with:
      #    keep_latest: 6
      #    delete_tags: true
