name: build-lede-24

on:
  repository_dispatch:
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  LEDE_REPO: https://github.com/coolsnowwolf/lede
  LEDE_BRANCH: master
  LEDE_CONFIG: ./config/lede/lede.conf
  LEDE_NAME: n60pro
  LEDE_IP: 192.168.10.1
  LEDE_SSID: 778v5
  LEDE_FIRMWARE_TAG: lede
  LEDE_UPLOAD_FIRMWARE: true
  LEDE_UPLOAD_RELEASE: true
  LEDE_UPLOAD_BIN_DIR: false
  TIME_ZONE: Asia/Shanghai
  DEVICE_NAME: netcore_n60-pro
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          #sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo -E apt -yqq update
          sudo -E apt -yqq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler dos2unix flex gawk gcc-multilib g++-multilib gettext genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool llvm lrzsz msmtp ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E apt -yqq autoremove --purge
          sudo -E apt -yqq clean
          #实际上，用下面这行可以替代上面的一些工作
          #sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
          sudo timedatectl set-timezone "$TIME_ZONE"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir

      #- name: Initialization environment
      #  env:
      #    DEBIAN_FRONTEND: noninteractive
      #  run: |
      #    sudo docker image prune --all --force
      #    sudo -E apt -yqq purge firefox
      #    sudo -E apt -yqq update
      #    sudo -E apt -yqq full-upgrade
      #    sudo -E apt -yqq autoremove --purge
      #    sudo -E apt -yqq autoclean
      #    sudo -E apt -yqq clean
      #    sudo -E apt -yqq install dos2unix python3-netifaces libfuse-dev
      #    sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
      #    sudo -E systemctl daemon-reload
      #    sudo -E timedatectl set-timezone "$TIME_ZONE"
      #    
      #    sudo mkdir -p /workdir
      #    sudo chown $USER:$USER /workdir
      #    sudo ln -s /workdir $GITHUB_WORKSPACE/openwrt

      - name: Initialization values
        run: |
          echo "LEDE_KVER=none" >> $GITHUB_ENV
          echo "LEDE_LIST=none" >> $GITHUB_ENV
          # df -hT $FIRMWARE_PATH是一个完整的shell命令，执行后$FIRMWARE_PATH会被替换为具体的路径值
          df -hT $FIRMWARE_PATH
          echo "LEDE_FIRMWARE_PATH=$FIRMWARE_PATH" >> $GITHUB_ENV

      - name: Clone source code
        working-directory: /workdir
        run: |
          git clone $LEDE_REPO -b $LEDE_BRANCH openwrt
          ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

      - name: Check scripts
        run: |
          # 为sh脚本赋予可执行权限
          # find ./ -maxdepth 4 -type f -iregex ".*\(txt\|sh\)$" -exec dos2unix {} \; -exec chmod +x {} \;
          # find ./ -maxdepth 4 -type f -iregex ".*\(sh\)$" -exec dos2unix {} \; -exec chmod +x {} \;
          find ./ -maxdepth 4 -type f -name "*.sh" -exec dos2unix {} \; -exec chmod +x {} \;

      - name: Update and install feeds
        run: |
          cd ./openwrt 
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Custom packages
        run: |
          # Check scripts中已授权，故注释掉下面两行
          # chmod +x $GITHUB_WORKSPACE/scripts/lede/packages.sh
          # chmod +x $GITHUB_WORKSPACE/scripts/lede/handles.sh
          cd ./openwrt/package/
          $GITHUB_WORKSPACE/scripts/lede/packages.sh
          $GITHUB_WORKSPACE/scripts/lede/handles.sh

      - name: Load custom configuration
        run: |
          [ -e files ] && mv files ./openwrt/files
          [ -e $LEDE_CONFIG ] && mv $LEDE_CONFIG ./openwrt/.config
          # Check scripts中已授权，故注释掉下面这行
          # chmod +x $GITHUB_WORKSPACE/scripts/lede/settings.sh
          cd ./openwrt
          $GITHUB_WORKSPACE/scripts/lede/settings.sh

      - name: Download package
        id: package
        run: |
          cd ./openwrt
          make defconfig
          make download -j16
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
          
      - name: Check disk space before compile firmware
        run: |
          echo "=== Disk space before compile firmware ==="
          df -h