name: build-oc-core

on:
  workflow_call:
    inputs:
      OC_CONFIG:
        required: true
        type: string
      OC_THEME:
        required: true
        type: string
      OC_NAME:
        required: true
        type: string
      OC_SSID:
        required: true
        type: string
      OC_WORD:
        required: true
        type: string
      OC_IP:
        required: true
        type: string
      OC_PW:
        required: true
        type: string
      OC_TAG:
        required: true
        type: string
      OC_REPO:
        required: true
        type: string
      OC_BRANCH:
        required: true
        type: string
      OC_SOURCE:
        required: true
        type: string
      OC_PACKAGE:
        required: false
        type: string

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  OC_CONFIG: ${{inputs.OC_CONFIG}}
  OC_THEME: ${{inputs.OC_THEME}}
  OC_NAME: ${{inputs.OC_NAME}}
  OC_SSID: ${{inputs.OC_SSID}}
  OC_WORD: ${{inputs.OC_WORD}}
  OC_IP: ${{inputs.OC_IP}}
  OC_PW: ${{inputs.OC_PW}}
  OC_TAG: ${{inputs.OC_TAG}}
  OC_REPO: ${{inputs.OC_REPO}}
  OC_BRANCH: ${{inputs.OC_BRANCH}}
  OC_SOURCE: ${{inputs.OC_SOURCE}}
  OC_PACKAGE: ${{inputs.OC_PACKAGE}}

jobs:
  core:
    name: ${{inputs.OC_SOURCE}}
    runs-on: ubuntu-latest
    steps:
      - name: Free disk space ubuntu-latest
        uses: BRAINSia/free-disk-space@main
        with:
          tool-cache: false
          mandb: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout projects
        uses: actions/checkout@main

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt -yqq purge firefox
          sudo -E apt -yqq update
          sudo -E apt -yqq full-upgrade
          sudo -E apt -yqq autoremove --purge
          sudo -E apt -yqq autoclean
          sudo -E apt -yqq clean
          sudo -E apt -yqq install dos2unix python3-netifaces libfuse-dev
          sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
          sudo -E systemctl daemon-reload
          sudo -E timedatectl set-timezone "Asia/Shanghai"

          sudo mkdir -p /mnt/build_wrt
          sudo chown $USER:$USER /mnt/build_wrt
          sudo ln -s /mnt/build_wrt $GITHUB_WORKSPACE/wrt

      - name: Initialization values
        run: |
          echo "OC_DATE=$(TZ=UTC-8 date +"%y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV
          echo "OC_MARK=${GITHUB_REPOSITORY%%/*}" >> $GITHUB_ENV
          echo "OC_INFO=${OC_SOURCE%%/*}" >> $GITHUB_ENV
          echo "OC_TARGET=$(grep -m 1 -oP '^CONFIG_TARGET_\K[\w]+(?=\=y)' ./config/padavanonly/padavanonly.conf)" >> $GITHUB_ENV
          echo "OC_KVER=none" >> $GITHUB_ENV
          echo "OC_LIST=none" >> $GITHUB_ENV

      - name: Clone code
        run: |
          git clone --depth=1 --single-branch --branch $OC_BRANCH $OC_REPO ./wrt/

          cd ./wrt/ && echo "OC_HASH=$(git log -1 --pretty=format:'%h')" >> $GITHUB_ENV

          # 如果不存在 defconfig 则直接结束工作流
          if [ ! -d "defconfig" ]; then
            echo "defconfig directory not found, stopping workflow."
            exit 0
          fi

          # GitHub Action 移除国内下载源
          PROJECT_MIRRORS_FILE="./scripts/projectsmirrors.json"
          if [ -f "$PROJECT_MIRRORS_FILE" ]; then
            sed -i '/.cn\//d; /tencent/d; /aliyun/d' "$PROJECT_MIRRORS_FILE"
          fi

      - name: Check scripts
        run: |
          find ./ -maxdepth 4 -type f -iregex ".*\(txt\|sh\)$" -exec dos2unix {} \; -exec chmod +x {} \;

      - name: Check caches
        id: check-cache
        uses: actions/cache@main
        with:
          key: ${{env.OC_CONFIG}}-${{env.OC_INFO}}-${{env.OC_HASH}}
          restore-keys: ${{env.OC_CONFIG}}-${{env.OC_INFO}}
          path: |
            ./wrt/.ccache
            ./wrt/staging_dir/host*
            ./wrt/staging_dir/tool*

      - name: Update caches
        run: |
          if [ -d "./wrt/staging_dir" ]; then
            find "./wrt/staging_dir" -type d -name "stamp" -not -path "*target*" | while read -r DIR; do
              find "$DIR" -type f -exec touch {} +
            done

            mkdir -p ./wrt/tmp && echo "1" > ./wrt/tmp/.build

            echo "toolchain skiped done!"
          else
            echo "caches missed!"
          fi

          if ${{steps.check-cache.outputs.cache-hit != 'true'}}; then
            CACHE_LIST=$(gh cache list --key "$OC_CONFIG-$OC_INFO" | cut -f 1)
            for CACHE_KEY in $CACHE_LIST; do
              gh cache delete $CACHE_KEY
            done

            echo "caches cleanup done!"
          fi

      - name: Update feeds
        run: |
          cd ./wrt/

          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Custom packages
        run: |
          cd ./wrt/package/

          $GITHUB_WORKSPACE/scripts/padavanonly/packages.sh
          $GITHUB_WORKSPACE/scripts/padavanonly/handles.sh

      - name: Custom settings
        run: |
          cd ./wrt/

          cat $GITHUB_WORKSPACE/config/padavanonly/padavanonly.conf >> .config

          $GITHUB_WORKSPACE/scripts/padavanonly/settings.sh

          make defconfig -j$(nproc) && make clean -j$(nproc)

      - name: Download packages
        run: |
          cd ./wrt/

          make download -j$(nproc)

      - name: Check disk space before compile firmware
        run: |
          echo "=== Disk Space Before Compile Firmware ==="
          df -h

      - name: Compile firmware
        run: |
          cd ./wrt/

          make -j$(nproc) || make -j1 || make -j1 V=s

      - name: Machine information
        run: |
          cd ./wrt/

          echo "======================="
          lscpu | grep -E "name|Core|Thread"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1
          echo "======================="

      - name: Package firmware
        run: |
          cd ./wrt/ && mkdir ./upload/

          cp -f ./.config ./upload/config-"$OC_CONFIG"-"$OC_INFO"-"$OC_BRANCH"-"$OC_DATE".txt

          echo "OC_KVER=$(find ./bin/targets/ -type f -name "*.manifest" -exec grep -oP '^kernel - \K[\d\.]+' {} \;)" >> $GITHUB_ENV
          echo "OC_LIST=$(find ./bin/targets/ -type f -name "*.manifest" -exec grep -oP '^luci-(app|theme)[^ ]*' {} \; | tr '\n' ' ')" >> $GITHUB_ENV
          find ./bin/targets/ -iregex ".*\(buildinfo\|json\|sha256sums\|packages\)$" -exec rm -rf {} +
          for FILE in $(find ./bin/targets/ -type f -iname "*$OC_TARGET*") ; do
            EXT=$(basename $FILE | cut -d '.' -f 2-)
            NAME=$(basename $FILE | cut -d '.' -f 1 | grep -io "\($OC_TARGET\).*")
            NEW_FILE="$OC_INFO"-"$OC_BRANCH"-"$NAME"-"$OC_DATE"."$EXT"
            mv -f $FILE ./upload/$NEW_FILE
          done
          find ./bin/targets/ -type f -exec mv -f {} ./upload/ \;
          make clean -j$(nproc)

      #   将生成的固件暂存到Artifact中，并保留30天，避免因GitHub Release上传失败而丢失固件
      # - name: Upload Firmware As Artifact
      #   uses: actions/upload-artifact@main
      #   with:
      #     name: firmware-${{ env.OC_CONFIG }}-${{ env.OC_INFO }}-${{ env.OC_BRANCH }}-${{ env.OC_DATE }}
      #     path: ./wrt/upload/
      #     retention-days: 90

      - name: Release firmware
        uses: softprops/action-gh-release@master
        with:
          # tag_name: ${{env.OC_CONFIG}}-${{env.OC_INFO}}-${{env.OC_BRANCH}}-${{env.OC_DATE}}
          tag_name: ${{env.OC_DATE}}-${{env.OC_TAG}}
          # files: ./wrt/upload/*.*
          files: |
            ./wrt/upload/mt7986-ram-ddr4-bl2.bin
            ./wrt/upload/padavanonly-openwrt-*.manifest
            ./wrt/upload/padavanonly-openwrt-*.bin
          body: |
            源码：${{env.OC_REPO}}
            分支：${{env.OC_BRANCH}}
            提交：${{env.OC_HASH}}

            配置：${{env.OC_CONFIG}}
            平台：${{env.OC_TARGET}}

            登录地址：${{env.OC_IP}}
            登录密码：${{env.OC_PW}}

            WIFI名称：${{env.OC_SSID}}
            WIFI密码：${{env.OC_WORD}}

            内核版本：${{env.OC_KVER}}
            插件列表：${{env.OC_LIST}}
